/**
 * Search index: every drug/calculation and the tile it lives on.
 * Kept as a flat static list so the header search can jump straight to the right tab.
 */
export const DRUG_INDEX = [
  // Emergency
  { n: "Adenosine", t: "emergency" },
  { n: "Adrenaline (asystole)", t: "emergency" },
  { n: "Adrenaline (anaphylaxis IV)", t: "emergency" },
  { n: "Adrenaline IM", t: "emergency" },
  { n: "Adrenaline aerosol (stridor)", t: "emergency" },
  { n: "Amiodarone", t: "emergency" },
  { n: "Atropine", t: "emergency" },
  { n: "Calcium gluconate", t: "emergency" },
  { n: "Calcium chloride (CaCl₂)", t: "emergency" },
  { n: "Lignocaine (arrhythmia)", t: "emergency" },
  { n: "Sodium bicarbonate (NaHCO₃)", t: "emergency" },
  { n: "Dantrolene (malignant hyperthermia)", t: "emergency" },
  // Induction
  { n: "Propofol", t: "induction" },
  { n: "Etomidate", t: "induction" },
  { n: "Ketamine", t: "induction" },
  { n: "Fentanyl", t: "induction" },
  { n: "Midazolam", t: "induction" },
  { n: "Rocuronium", t: "induction" },
  { n: "Cisatracurium", t: "induction" },
  { n: "Sugammadex", t: "induction" },
  { n: "Neostigmine", t: "induction" },
  { n: "Glycopyrrolate", t: "induction" },
  { n: "Reversal mix (Red Cross)", t: "induction" },
  // Analgesia
  { n: "Paracetamol", t: "analgesia" },
  { n: "Ketorolac", t: "analgesia" },
  { n: "Metamizole", t: "analgesia" },
  { n: "Tramadol", t: "analgesia" },
  { n: "Morphine", t: "analgesia" },
  { n: "Ondansetron", t: "analgesia" },
  { n: "Dexamethasone", t: "analgesia" },
  { n: "Gabapentin", t: "analgesia" },
  // Fluids
  { n: "Maintenance fluids (4/2/1)", t: "fluids" },
  { n: "Fasting rule (1–4–6)", t: "fluids" },
  { n: "Plasmalyte bolus", t: "fluids" },
  { n: "Albumin 4% bolus", t: "fluids" },
  // Regional
  { n: "Lidocaine (LA max dose)", t: "regional" },
  { n: "Levobupivacaine", t: "regional" },
  { n: "Ropivacaine", t: "regional" },
  { n: "Bupivacaine caudal", t: "regional" },
  { n: "Epidural", t: "regional" },
  { n: "Wound infusion catheter", t: "regional" },
  { n: "Clysis (field block)", t: "regional" },
  // Standard
  { n: "Ephedrine", t: "standard" },
  { n: "Phenylephrine", t: "standard" },
  { n: "Noradrenaline bolus/infusion", t: "standard" },
  { n: "Dexmedetomidine", t: "standard" },
  { n: "Clonidine", t: "standard" },
  { n: "Diazepam", t: "standard" },
  { n: "Glucose 10%", t: "standard" },
  { n: "Hydrocortisone", t: "standard" },
  { n: "Methylprednisolone", t: "standard" },
  { n: "Potassium (KCl)", t: "standard" },
  { n: "Magnesium (MgSO₄)", t: "standard" },
  { n: "Mannitol 20%", t: "standard" },
  { n: "Naloxone", t: "standard" },
  { n: "Cefazolin", t: "standard" },
  { n: "Salbutamol + Ipratropium", t: "standard" },
  { n: "Tranexamic acid", t: "standard" },
  { n: "Valproate", t: "standard" },
  // Airway & Lines
  { n: "ETT size & depth", t: "airway" },
  { n: "LMA size", t: "airway" },
  { n: "Defibrillation energy", t: "airway" },
  { n: "Cardioversion energy", t: "airway" },
  { n: "CVC size & depth", t: "airway" },
  // Inotropes
  { n: "Adrenaline infusion", t: "inotropy" },
  { n: "Noradrenaline infusion", t: "inotropy" },
  { n: "Dobutamine", t: "inotropy" },
  { n: "Dopamine", t: "inotropy" },
  { n: "Milrinone", t: "inotropy" },
  { n: "Vasopressin", t: "inotropy" },
  // Transfusion
  { n: "Red cells (RBC)", t: "transfusion" },
  { n: "Plasma (FFP)", t: "transfusion" },
  { n: "Platelets", t: "transfusion" },
  { n: "Fibrinogen (RiaStap)", t: "transfusion" },
  { n: "Massive transfusion (MTP)", t: "transfusion" },
  { n: "Blood volume / allowable loss", t: "transfusion" },
  // TIVA
  { n: "Propofol TIVA / TCI", t: "tiva" },
  { n: "Remifentanil infusion", t: "tiva" },
  { n: "Ketamine TIVA", t: "tiva" },
  // Abx & Misc
  { n: "Amikacin", t: "addendum" },
  { n: "Amoxicillin (+Clav)", t: "addendum" },
  { n: "Ceftazidime", t: "addendum" },
  { n: "Clindamycin", t: "addendum" },
  { n: "Metronidazole", t: "addendum" },
  { n: "Tobramycin", t: "addendum" },
  { n: "Vancomycin", t: "addendum" },
  { n: "Sufentanil", t: "addendum" },
  { n: "Caffeine citrate", t: "addendum" },
];
